training_dataset = [
    "Vinos tintos",
    "El vino tinto a menudo se define por sus taninos y sabores de frutas negras, lo que lo convierte en un buen complemento para una amplia variedad de alimentos. Los taninos son compuestos responsables de la sequedad en boca y el amargor del vino. El roble también juega un papel muy importante en el proceso de envejecimiento de la mayoría de los vinos tintos.\n El vino tinto se puede elaborar con un solo tipo de uva tinta o uvas de piel negra con jugo incoloro. Sabrás el tipo de uva utilizada en la etiqueta de la botella. La mayoría de las veces, el nombre de la variedad de uva se basa en la región en la que se cultivaron. Por ejemplo, Shiraz es la variedad llamada para uvas cultivadas y recolectadas en el Syrah francés en Australia, otros que puedan sonarte más si eres de España son los «Rioja» o «Rivera de duero».\nUna vez prensada la uva en la bodega, se mezclan los hollejos de la uva con el mosto. Esto le da al vino tinto su característico color púrpura rojizo y le da taninos. Luego se colocan en barriles de roble donde se agregan con especias dulces para hornear, vainilla, chocolate y cacao. Además, la crianza en barrica de roble suaviza la estructura tánica del vino tinto, dándole un sabor más suave.\nLos taninos de las variedades de vino tinto sirven como conservante, lo que significa que los vinos tintos con altos niveles de taninos pueden envejecer más tiempo en comparación con los vinos blancos. A medida que envejecen, las antocianinas y los taninos del vino tinto se desprenden y forman sedimentos en el fondo. Estos sedimentos pueden eliminarse por decantación.\nSi deseas disfrutar de una copa de vino tinto, algunas buenas variedades incluyen Syrah, Cabernet Sauvignon, Garnacha, Garnacha Tintorera o Alicante, Graciano, Malbec, Merlot, Monastrell, Pinot Noir o Tempranillo entre otros.",
    
    "Vinos Blancos",
    "Estos están hechos de uvas de piel verde con jugo incoloro. Para la elaboración del vino blanco, se retiran los hollejos de las uvas antes del proceso de fermentación. Por eso tiene un color claro y blanco, a diferencia del vino tinto.\nEl aroma y la estructura ácida son más evidentes en los vinos blancos porque no tienen los taninos que tienen los vinos tintos. Los vinos blancos se elaboran típicamente a partir de una combinación de uvas que son comunes en áreas como Burdeos, España y el sur del Ródano de Francia.\nLa mayoría de los vinos blancos se envejecen en un barril de acero inoxidable, lo que ayuda a mantener sus aromas frescos. Sin embargo, el envejecimiento en roble aún se puede usar si el fabricante desea agregar sabores y aromas de vainilla, caramelo, coco y especias para hornear al vino.\nEn términos de sabor, los vinos blancos pueden variar de dulces a secos.",

    "Vinos Rosados",
    "La mayoría de la gente piensa que los vinos rosados se crean combinando vinos blancos y tintos. Sin embargo, en realidad están hechos de variedades de uva tinta. Para la elaboración del vino rosado, uno de los métodos utilizados es la maceración en la que se prensa la uva roja y se deja en remojo el mosto producido junto con la piel de la uva. El color del vino puede oscurecerse dependiendo de cuánto tiempo estuvieron empapadas las uvas con su piel. Es por eso que el color de los vinos rosados ​​suele oscilar entre el rubor rosado y un rosa intenso.",

]
{
    'import_path': 'chatterbot.logic.SpecificResponseAdapter',
    'input_text': 'Help',
    'output_text': 'Ok, here is a link: https://vakilsearch.com/'
}
